name: Build and Test

on: [push] # هر وقت کدی push کردی، اجرا می‌شود

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive # این خیلی مهمه تا کتابخانه‌ها دانلود بشن

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run Build
        run: |
          forge --version
          forge install OpenZeppelin/openzeppelin-contracts --no-commit
          forge build
